[tasks.fix-spelling]
run = "typos --write-changes"

[tasks.format-markdown]
run = "dprint fmt"
# Mise uses this config file's location as the CWD
dir = "../../"

[tasks.pr-all]
run = [
    "mise run pr-spell-check",
    "mise run pr-markdown",
]

[tasks.pr-markdown]
run = "dprint check"
# Mise uses this config file's location as the CWD
dir = "../../"

[tasks.pr-spell-check]
run = "typos"

[tools]
"cargo:dprint" = "0.51"
"cargo:typos-cli" = "1.36"

[env]
_.file = '../../.env'
